#!/bin/bash
source /etc/passmang/passmang_config.sh
# filepath=/usr/local/share/passmang/ltwrd 
# binpath=/usr/local/bin/passmang_core

if [[ $# -eq 1 ]] && [[ $1 == "encrypt" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      $binpath encrypt $filepath $masterpass 
elif [[ $# -eq 1 ]] && [[ $1 == "decrypt" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      $binpath decrypt $filepath $masterpass 
elif [[ $# -eq 2 ]] && [[ $1 == "get" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      get_output=$($binpath get $filepath $masterpass $2)
      if [[ ! $get_output ]]; then 
	printf "No match!\n" 
      else
	printf $get_output|xclip -selection c
      fi
#|xclip -selection c
elif [[ $# -eq 2 ]] && [[ $1 == "del" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      $binpath del $filepath $masterpass $2
elif [[ $# -eq 3 ]] && [[ $1 == "add" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      $binpath add $filepath $masterpass $2 $3
elif [[ $# -eq 3 ]] && [[ $1 == "mod" ]]; 
then 
      read -sp "Masterpass: " masterpass
      printf "Entered\n"
      $binpath mod $filepath $masterpass $2 $3
else
      cat << EOF
      * Commands: 
      * 1) passmang encrypt 
      * 2) passmang decrypt
      * 3) passmang get key
      * 4) passmang del key
      * 5) passmang mod key password
      * 6) passmang add key password
      * After each command you will be prompted for the master password. 
      * 
      * Command Details:
      * 1) Encrypting a plaintext file (asks for masterpass)
      * 2) Decrypting an encrypted file (asks for filepath, masterpass)
      * 3) Getting a key-pass entry from a file (asks for filepath, masterpass, key)
      * 4) Deleting a key-pass entry from a file (asks for filepath, masterpass, key)
      * 5) Editing a key-pass entry from a file (asks for filepath, masterpass, key, password)
      * 6) Adding a key-pass entry to a file (asks for filepath, masterpass, key, password
      *
      * Troubleshooting: 
      * If for any reason you need to decrypt your file, execute command 2) below and your text file will show up as passfile_1
      

EOF

fi
